# EDA DE DATA SINTÉTICA

In [15]:
import numpy as np
import pandas as pd

### EVENTOS

In [16]:
eventos = pd.read_csv("data_sintetica\datos_eventos.csv")
eventos

,Id_user,Sexo,Edad,Municipio,Concierto_Festival,Fiestas_Feria,Teatro,Danza,Conferencia_Jornadas_Presentacion,Cine_Audiovisuales,Bertsolarismo,Exposicion,Formacion,Concurso,Target_Review
0,U00001,F,70,Bilbao,0,1,1,1,1,1,1,1,0,0,4
1,U00002,F,48,Vitoria-Gasteiz,1,1,0,0,1,1,1,0,0,1,3
2,U00003,M,57,Portugalete,1,0,1,0,0,1,0,0,0,1,4
3,U00004,M,49,Llodio,1,0,1,1,0,1,1,1,0,1,4
4,U00005,F,64,Vitoria-Gasteiz,1,1,0,1,1,1,1,1,0,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,U01996,M,46,Donostia-San Sebastián,1,1,1,0,0,1,1,1,0,1,4
1996,U01997,F,64,Bilbao,1,1,1,0,0,1,0,1,1,0,3
1997,U01998,M,63,Vitoria-Gasteiz,1,1,0,1,1,1,1,1,0,0,4
1998,U01999,M,52,Getxo,1,1,1,1,0,1,0,1,0,0,3
1999,U02000,F,48,Vitoria-Gasteiz,1,1,0,0,0,1,0,1,0,0,3

In [17]:
eventos.describe()

,Edad,Concierto_Festival,Fiestas_Feria,Teatro,Danza,Conferencia_Jornadas_Presentacion,Cine_Audiovisuales,Bertsolarismo,Exposicion,Formacion,Concurso,Target_Review
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000
mean,54.478000,0.632500,0.604000,0.619000,0.495500,0.487000,0.652000,0.568000,0.628000,0.496000,0.367000,3.609500
std,8.389917,0.482245,0.489187,0.485754,0.500105,0.499956,0.476455,0.495478,0.483459,0.500109,0.482107,0.590071
min,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000
25%,49.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000
50%,55.000000,1.000000,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,4.000000
75%,61.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,4.000000
max,75.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,5.000000

### GASTRONOMÍA

In [18]:
gastro = pd.read_csv("data_sintetica\datos_gastronomia.csv")
gastro

,Id_user,Sexo,Edad,Municipio,Restaurantes,Restaurantes_Restaurante,Restaurantes_Asador,Restaurantes_Sidreria,Bodegas,Questerias,Gourmet,Gourmet_Agricultura_ecologica,Gourmet_Denominacion_de_Origen,Gourmet_Eusko_Label,Gourmet_Euskal_Baserri,Target_Review
0,U00001,F,70,Bilbao,1,1,1,1,1,1,1,1,1,1,1,4
1,U00002,F,67,Bilbao,1,0,1,0,1,1,1,0,1,1,1,5
2,U00003,M,57,Portugalete,1,0,1,0,1,1,0,0,0,0,0,3
3,U00004,F,54,Bilbao,1,1,1,1,0,0,0,0,0,0,0,3
4,U00005,M,57,Vitoria-Gasteiz,1,1,1,0,0,1,1,1,1,1,1,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,U01996,M,48,Beasain,0,0,0,0,1,1,0,0,0,0,0,3
1996,U01997,M,45,Bilbao,1,1,1,1,0,0,1,0,0,0,1,3
1997,U01998,M,60,Beasain,1,1,1,0,0,0,1,1,1,1,1,4
1998,U01999,F,55,Tolosa,1,0,1,0,1,1,1,0,1,0,1,3
1999,U02000,F,61,Bilbao,1,0,1,1,1,1,1,0,1,1,1,4

In [19]:
gastro.describe()

,Edad,Restaurantes,Restaurantes_Restaurante,Restaurantes_Asador,Restaurantes_Sidreria,Bodegas,Questerias,Gourmet,Gourmet_Agricultura_ecologica,Gourmet_Denominacion_de_Origen,Gourmet_Eusko_Label,Gourmet_Euskal_Baserri,Target_Review
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.00000,2000.000000,2000.000000,2000.00000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000
mean,54.496000,0.870000,0.655500,0.621000,0.58250,0.609000,0.568000,0.68700,0.421500,0.456000,0.492500,0.489500,3.617500
std,8.420299,0.336388,0.475324,0.485259,0.49327,0.488096,0.495478,0.46383,0.493923,0.498185,0.500069,0.500015,0.670387
min,25.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,2.000000
25%,49.000000,1.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,3.000000
50%,55.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.00000,0.000000,0.000000,0.000000,0.000000,4.000000
75%,61.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,4.000000
max,75.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,5.000000

### LUGARES DE INTERÉS

In [20]:
lugares = pd.read_csv("data_sintetica\datos_lugares_interes.csv")
lugares

,Id_user,Sexo,Edad,Municipio,Museos,Museos_Historia,Museos_Ciencias_Naturales,Museos_Arte,Museos_Etnografia,Patrimonio_cultural,Target_Review
0,U00001,F,70,Bilbao,1,1,1,1,1,1,4
1,U00002,F,59,Irun,1,1,1,0,1,0,3
2,U00003,M,47,Vitoria-Gasteiz,1,1,1,1,1,1,4
3,U00004,F,53,Bilbao,1,1,1,1,0,0,4
4,U00005,F,49,Zarautz,1,1,1,1,1,1,4
...,...,...,...,...,...,...,...,...,...,...,...
1995,U01996,F,61,Azpeitia,1,0,1,0,0,0,3
1996,U01997,M,58,Basauri,1,0,0,0,1,1,3
1997,U01998,M,52,Vitoria-Gasteiz,1,0,1,1,1,1,5
1998,U01999,M,63,Barakaldo,1,1,1,0,0,1,4
1999,U02000,M,69,Santurtzi,1,1,1,1,1,1,5

In [21]:
lugares.describe()

,Edad,Museos,Museos_Historia,Museos_Ciencias_Naturales,Museos_Arte,Museos_Etnografia,Patrimonio_cultural,Target_Review
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000
mean,54.234500,0.770500,0.553000,0.397500,0.540000,0.494500,0.773000,3.666000
std,8.543946,0.420616,0.497307,0.489503,0.498522,0.500095,0.418997,0.761403
min,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,49.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,3.000000
50%,55.000000,1.000000,1.000000,0.000000,1.000000,0.000000,1.000000,4.000000
75%,60.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,4.000000
max,75.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,5.000000