In [26]:
import requests
import json
import pandas as pd
import numpy as np
import os

In [27]:
df_user = pd.read_csv("data/usuarios.csv")
df_user

,id_user,nombre,apellido,email,password_hash,tlf,municipality_id,sexo,age,role,created_at,updated_at
0,1,Ander,Martin Alonso,ander.martin1075@euskador.eus,0d6e670ed0489d3dd6fe00c0113f7464203a0240c5e0b4...,+34 98266521,20055,hombre,47,user,2026-03-16 10:22:00,2026-03-16 10:22:00
1,2,Daniel,Agirre Ruiz,daniel.agirre849@euskador.eus,efc20d1042848eb9674b1a9a339abeeb96cc98935f488c...,+34 97389339,48015,hombre,58,user,2026-03-20 13:43:00,2026-03-20 13:43:00
2,3,Joseba,Garate Moreno,joseba.garate897@euskador.eus,dc00655e589390cd9ed0ebf7f0a33176829bafa0ae9ce6...,+34 69278928,48027,hombre,45,user,2026-03-18 06:39:00,2026-03-18 06:39:00
3,4,Carmen,González Goikoetxea,carmen.gonzalez225@euskador.eus,a7d8680c5e5641800b0e47c63d32971def5487a274f483...,+34 71486009,48015,mujer,65,user,2026-03-07 11:31:00,2026-03-07 11:31:00
4,5,Itziar,Larrañaga Alonso,itziar.larranaga419@euskador.eus,13df7d7f2c511b6bc07133adfa895e57e089fe45e08c37...,+34 76041284,48011,mujer,60,user,2026-03-28 04:40:00,2026-03-28 04:40:00
...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1996,Manuel,Mendizabal Arregi,manuel.mendizabal204@euskador.eus,383f992cd7c848cc4f053cac521f03502541ac4a50898c...,+34 74645676,48011,hombre,47,user,2026-03-09 13:59:00,2026-03-09 13:59:00
1996,1997,Imanol,Muñoz Zabaleta,imanol.munoz123@euskador.eus,95392d1f2ad36f998695e78e63a19d33740b138711d83f...,+34 98719044,48003,hombre,54,user,2026-03-28 08:13:00,2026-03-28 08:13:00
1997,1998,Iñaki,Goikoetxea Barandiaran,inaki.goikoetxea1517@euskador.eus,7c93c49fc521604ae3f6c9e7144a4c4edfbc0ef503a9a7...,+34 65387151,20055,hombre,63,user,2026-03-28 15:54:00,2026-03-28 15:54:00
1998,1999,Miren,Goikoetxea Basabe,miren.goikoetxea1707@euskador.eus,bd9ac7b1d4dd6b10cdcd4870a792cda2b7696e349f42b0...,+34 73993656,1043,mujer,58,user,2026-03-18 09:40:00,2026-03-18 09:40:00
1999,2000,Manuel,Goikoetxea Martínez,manuel.goikoetxea59@euskador.eus,f18bc895766b16f56bb5f6363588eb72eae5f134493a3d...,+34 95645769,48015,hombre,64,user,2026-03-23 06:34:00,2026-03-23 06:34:00

In [30]:
df_user.drop(columns=["nombre", "apellido", "email", "password_hash", "tlf", "role", "created_at", "updated_at"], inplace=True)

In [18]:
df_user

      id_user  municipality_id    sexo  age
0           1            20055  hombre   47
1           2            48015  hombre   58
2           3            48027  hombre   45
3           4            48015   mujer   65
4           5            48011   mujer   60
...       ...              ...     ...  ...
1995     1996            48011  hombre   47
1996     1997            48003  hombre   54
1997     1998            20055  hombre   63
1998     1999             1043   mujer   58
1999     2000            48015  hombre   64

[2000 rows x 4 columns]

In [35]:
#listamos las columnas de df_user
print("df_user columns:", df_user.columns.tolist())

df_user columns: ['id_user', 'municipality_id', 'sexo', 'age']

In [28]:
df_intereses = pd.read_csv("data/intereses.csv")
df_intereses

    id_interes                                       nombre  father_id  level
0            1                                      Eventos        NaN      0
1            2                                  Gastronomía        NaN      0
2            3                            Puntos de interés        NaN      0
3            4                         Concierto y Festival        1.0      1
4            5                              Fiestas y Feria        1.0      1
5            6                                       Teatro        1.0      1
6            7                                        Danza        1.0      1
7            8  Conferencia, Eventos/jornadas, Presentación        1.0      1
8            9                         Cine y audiovisuales        1.0      1
9           10                                Bertsolarismo        1.0      1
10          11                                   Exposición        1.0      1
11          12                                    Formación        1.0      1
12          13                                     Concurso        1.0      1
13          14                                   Hostelería        2.0      1
14          15                                    Queserías        2.0      1
15          16                                      Gourmet        2.0      1
16          17                                  Restaurante       14.0      2
17          18                                       Asador       14.0      2
18          19                                     Sidrería       14.0      2
19          20                                      Bodegas       14.0      2
20          21                        Agricultura ecológica       16.0      2
21          22                       Denominación de Origen       16.0      2
22          23                                  Eusko Label       16.0      2
23          24                               Euskal Baserri       16.0      2
24          25                             Museos: Historia        3.0      1
25          26                           Ciencias naturales        3.0      1
26          27                                         Arte        3.0      1
27          28                                   Etnografía        3.0      1
28          29                          Patrimonio cultural        3.0      1

In [29]:
df_user_interes = pd.read_csv("data/intereses_usuarios.csv")
df_user_interes

      id_user  id_interes
0           1          14
1           1          17
2           1          20
3           1          27
4           1          29
...       ...         ...
9167     2000           8
9168     2000          14
9169     2000          17
9170     2000          20
9171     2000          29

[9172 rows x 2 columns]

In [ ]:
# unimos df_user_interes con df_user (por id_user) y con df_intereses (por id_interes)
# luego generamos un one-hot encoding con los intereses como columnas conservando las columnas de df_user
user_cols = ["id_user", "municipality_id", "sexo", "age"]

df_user_total = (
    df_user_interes
    .merge(df_user, on="id_user")
    .merge(df_intereses[["id_interes", "nombre"]], on="id_interes")
    .drop(columns=["id_interes"])
)

df_user_total = (
    df_user_total
    .pivot_table(index=user_cols, columns="nombre", aggfunc="size", fill_value=0)
    .reset_index()
)

df_user_total.columns.name = None
df_user_total

,id_user,Agricultura ecológica,Arte,Asador,Bertsolarismo,Bodegas,Ciencias naturales,Cine y audiovisuales,Concierto y Festival,Concurso,...,Fiestas y Feria,Formación,Gourmet,Hostelería,Museos: Historia,Patrimonio cultural,Queserías,Restaurante,Sidrería,Teatro
0,1,0,1,0,0,1,0,0,0,0,...,0,0,0,1,0,1,0,1,0,0
1,2,0,1,0,0,1,0,0,0,0,...,0,0,0,1,0,1,0,1,0,0
2,3,0,1,1,0,0,0,0,0,0,...,0,0,0,1,0,1,0,1,0,0
3,4,0,1,1,0,1,0,0,0,0,...,0,0,0,1,0,1,0,1,0,1
4,6,0,1,1,0,1,0,0,0,0,...,0,0,0,1,0,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1595,1995,0,1,1,0,0,0,0,0,0,...,0,0,0,1,0,1,0,1,0,1
1596,1996,0,1,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0
1597,1998,0,1,0,0,1,0,0,0,0,...,0,0,0,1,0,1,0,0,0,1
1598,1999,0,0,1,0,1,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
1599,2000,0,0,0,0,1,0,0,0,0,...,0,0,0,1,0,1,0,1,0,0

df_intereses columns: ['id_interes', 'nombre', 'father_id', 'level']
df_user columns: ['id_user', 'municipality_id', 'sexo', 'age']
df_user_interes columns: ['id_user', 'id_interes']